### ISSUE TITLE
TODO | 未来计划

### ISSUE THREAD

**Issue by wallleap** [wallleap/ethereal#1]
以下暂时没有优先级

- [x] 更新使用文档
- [x] 添加文章中图片点击预览
- [ ] 抽离共用样式
- [x] 重写 SvgIcon 组件，适配暗黑模式
- [x] 使用 Front-matter 自定义创建时间后归档页排序问题
- [x] 文章页面部分块级标签未添加 margin（例如 div、options）
- [x] 关于页点赞 bug

**Comment by Meekdai** [comment]
你好，我想问一下，你们的这种展示图片是怎么制作的啊？
https://github.com/wallleap/ethereal/blob/main/docs/imgs/mockup.png

**Comment by wallleap** [comment]
> 你好，我想问一下，你们的这种展示图片是怎么制作的啊？
> https://github.com/wallleap/ethereal/blob/main/docs/imgs/mockup.png

你到素材网站搜【mockup】或【样机】，然后到设计软件里替换图片就行。如果不会 PS，可以去 Figma 社区搜

**Comment by Meekdai** [comment]
@wallleap 谢谢，已经做好了。另外已经添加大佬的友链 [link](https://blog.meekdai.com/link.html)

**Comment by wallleap** [comment]
> @wallleap 谢谢，已经做好了。另外已经添加大佬的友链 [link](https://blog.meekdai.com/link.html)

好的咧，已添加友链

**Comment by JIeJaitt** [comment]
想问一下这种以GitHub issue的博客是不是issue的那个仓库必须公开？

**Comment by wallleap** [comment]
> 想问一下这种以GitHub issue的博客是不是issue的那个仓库必须公开？

应该是不用的，设置成 private 通过请求 GitHub API 并且携带了 Token 是能获取到的
